name: Integration Test
permissions:
  contents: read
  pull-requests: write

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5.5.0
        with:
          python-version: "3.9"

      - name: Lint
        run: |
          pip install flake8
          cd src/github-action && flake8 *.py

      - name: Tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=github-action --pyargs github-action