name: Pull Request Labeler
on: pull_request_target

jobs:
  labeler:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jfheinrich-eu/psono-secret-whisperer@v1.0.0
        id: psono-secrets
        with:
            ci_api_key_id: ${{ secrets.PSONO_API_KEY_ID }}
            ci_api_secret_key_hex: ${{ secrets.PSONO_API_SECRET_KEY_HEX }}
            ci_server_url: ${{ vars.PSONO_SERVER_URL }}
            secret_id: ${{ secrets.PSONO_GITHUB_COM_TOKEN }}
            secret_type: 'secret'
            secret_fields: 'password'
            mask_secrets: 'password'

      - uses: actions/labeler@v5
        with:
          repo-token: ${{ steps.psono-secrets.outputs.secret1 }}

