name: Pull Request Labeler
permissions:
  contents: read
  pull-requests: write
on: pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr_labeler.yml
          sync-labels: false
