name: Lint
permissions:
  contents: write
  pull-requests: write

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v5.5.0
        with:
          python-version: "3.9"

      - uses: actions/checkout@v4

      - name: Lint
        run: |
          pip install flake8
          flake8 main.py

      - name: Automatic requirements.txt for Python Project
        uses: jfheinrich-eu/pipreqs-action@v4.2.1
        with:
          PROJECT_PATH: .
          REQUIREMENT_PATH: requirements.txt
          RECURSIVE: "false"

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'requirements.txt'

      - name: Commit changes
        if: steps.changes.outputs.src == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref_name }}
          commit_message: 'Updated requirements file on ${{ github.ref_name }} [skip-ci]'
          file_pattern: requirements.txt

