name: Create new release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch secrets
        id: fetch_secrets
        uses: jfheinrich-eu/psono-secret-whisperer@v1.0.0
        with:
          ci_api_key_id: ${{ secrets.PSONO_API_KEY_ID }}
          ci_api_secret_key_hex: ${{ secrets.PSONO_API_SECRET_KEY_HEX }}
          ci_server_url: ${{ vars.PSONO_SERVER_URL }}
          secret_id: ${{ secrets.RELEASE_WORKFLOW_TOKEN }}
          secret_type: 'secret'
          secret_fields: 'password'
          mask_secrets: 'password'

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: 'Release ${{ github.ref_name }}'
          body: ${{ steps.changelog.outputs.changes }}

      - name: Commit CHANGELOG.md
        if: ${{ github.ref }} == 'refs/heads/main'
        uses: Amraneze/push-to-protected-branch@v1.5.0
        with:
          repository: ${{ github.repository }}
          branch_name: main
          github_token: ${{ steps.fetch_secrets.outputs.secret1 }}
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} on ${{ github.ref }} [skip ci]'
          files_to_commit: CHANGELOG.md
