name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  bump-tag-version:
    name: Bump and Tag Version
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      PSONO_CI_API_KEY_ID: ${{ secrets.PSONO_API_KEY_ID }}
      PSONO_CI_API_SECRET_KEY_HEX: ${{ secrets.PSONO_API_SECRET_KEY_HEX }}
      PSONO_CI_SERVER_URL: ${{ vars.PSONO_SERVER_URL }}
      PSONO_GITHUB_TOKEN_ID: ${{ secrets.PSONO_GITHUB_CLI_TOKEN}}

    steps:
      - uses: actions/checkout@v4

      - name: Fetch secrets
        id: fetch-secrets
        uses: jfheinrich-eu/psono-secret-whisperer@v1.0.0
        with:
          ci_api_key_id: ${{ secrets.PSONO_API_KEY_ID }}
          ci_api_secret_key_hex: ${{ secrets.PSONO_API_SECRET_KEY_HEX }}
          ci_server_url: 'https://your-psono-server.com'
          secret_id: ${{ secrets.PSONO_GITHUB_CLI_TOKEN }}
          secret_type: 'secret'
          secret_fields: 'password'
          mask_secrets: 'password'

      - uses: jefflinse/pr-semver-bump@v1.7.2
        name: Bump and Tag Version
        with:
          mode: bump
          repo-token: ${{ steps.fetch-secrets.outputs.secret1 }}
          major-label: major release
          minor-label: minor release
          patch-label: patch release
          noop-labels: |
            documentation change
            skip-release
            dependencies
          require-release-notes: true
          release-notes-prefix: '<!--- START AUTOGENERATED NOTES --->'
          release-notes-suffix: '<!--- END AUTOGENERATED NOTES --->'
          with-v: true
          base-branch: false